### ISSUE TITLE
Logo Design For Sheasy

### ISSUE THREAD

**Issue by zularizal** [Foso/Sheasy#8]
Hi @Foso , I'm a graphic designer. I like your project,  I want to contribute by creating a free logo for your project. What do you think?

**Comment by Foso** [comment]
HI @zularizal , thank you, this would be awesome :smiley:

**Comment by zularizal** [comment]
Hi @Foso , here are some design logos for your project. These logos are inspired by the share icon, arrow and file icon.

What do you like? If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/55700030-e37e2500-59f7-11e9-9fc5-c041561623c2.png)

**Comment by Foso** [comment]
Hi @zularizal  , thank your for your ideas. I like them all, but the third one the most. :smiley:

**Comment by zularizal** [comment]
Hi @Foso , I have sent a pull request. #9 

And also I have uploaded the logo to the drive. Check this link
https://drive.google.com/open?id=1U_BL9KBX4DZw2TzS6RO7IFFgiH8r2rSp

**Comment by Foso** [comment]
Thank you for the icon and the PR, i merged it.
